### PR TITLE
Added ASCII Art

### PR DESCRIPTION
**Pull request by camconn**
- ASCII Art was generated with figlet
- Very nice Art
- Ayy Lmao

`ayy lmao`

### CODE REVIEW

**Comment by inexist3nce** [comment]
lol thanks

**Comment by inexist3nce** [comment]
asdasd

**Comment by inexist3nce** [comment]
asdc

**Comment by camconn** [comment]
testing for inex

**Comment by inexist3nce** [comment]
gerdfgb

**Comment by inexist3nce** [comment]
dfgv

**Comment by inexist3nce** [comment]
sewdfvc

**Comment by inexist3nce** [comment]
gfrdb

**Comment by inexist3nce** [comment]
YES IT WORKS

**Pull request merged**
